version: '3.8'
services:
  dev-db:
    image: postgres:13.2
    container_name: dev-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: purr-fact
    ports:
      - 5434:5432
    networks:
      - purr-fact
networks:
  purr-fact: